version : '3.7'
services :
  web :
    #build: .
    image: hasmukhrathod/rails_app:prod
    ports:
      - 80:3000
    ##make changes in the local & it will reflect to the container.
    #volumes:
      #- .:/usr/src/app
      #- gem_cache:/gems
    env_file:
      - .env/production/database
      - .env/production/web
  redis:
    image: redis
  db:
    image: postgres
    env_file:
      - .env/production/database
    volumes:
      - db_data:/var/lib/postgresql/data
  db-migrator:
    image: hasmukhrathod/rails_app:prod
    command: ["./wait-for", "--timeout=300", "db:5432", "--", "bin/rails", "db:migrate"]
    env_file:
      - .env/production/database
      - .env/production/web
volumes:
  db_data:
  #gem_cache:
