version : '3.7'
services :
  web :
    build: .
    ports:
      - 3000:3000
    ##make changes in the local & it will reflect to the container.
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web
  redis:
    image: redis
  db:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  gem_cache:
