version : '3.7'
services :
  web :
    build: .
    ports:
      - 3000:3000
    ##make changes in the local & it will reflect to the container.
    volumes:
      - .:/usr/src/app
  redis:
    image: redis
